pack_id: offline-daily-life-pack
default_metadata:
  domain: "general-public-assistant"
  language: "en"
sources:
  - url: https://en.wikipedia.org/wiki/Weather
    metadata:
      topic: "weather"
  - url: https://en.wikipedia.org/wiki/Navigation
    metadata:
      topic: "navigation"
  - url: https://en.wikipedia.org/wiki/Emergency_service
    metadata:
      topic: "emergency-services"
  - url: https://en.wikipedia.org/wiki/Map
    metadata:
      topic: "maps"
chunk_size: 5000
chunk_overlap: 540
summary_model: gpt-oss-120b
summary_max_words: 500
summarization_enabled: true
# qdrant_url and qdrant_api_key are read from env vars (QDRANT_URL, QDRANT_API_KEY)
embedding_model_name: sentence-transformers/all-MiniLM-L6-v2
batch_size: 16
