pack_id: emergency-field-pack
default_metadata:
  domain: "emergency-response"
  language: "en"
sources:
  - url: https://en.wikipedia.org/wiki/Hyperbaric_medicine
    metadata:
      topic: "hyperbaric"
  - url: https://en.wikipedia.org/wiki/First_aid
    metadata:
      topic: "first-aid"
chunk_size: 5000
chunk_overlap: 540
summary_model: gpt-oss-120b
summary_max_words: 500
summarization_enabled: true
# qdrant_url and qdrant_api_key are read from env vars (QDRANT_URL, QDRANT_API_KEY)
embedding_model_name: sentence-transformers/all-MiniLM-L6-v2
batch_size: 16
